### ISSUE TITLE
Vorbis encoding - .ogg file

### ISSUE THREAD

**Issue by gbdomubpkm** [luksus42/recorder#11]
the Vorbis encoding (.ogg file) is not recognised as an audio file: it corresponds to a 'Matroska stream' which displays the ogg file with a video file icon: the ogg files of the app recorder are not sendable with app messaging. Would it be possible to have the ogg format in your app shown as an audio file ( like the test file of @lduboeuf )?
see discussion https://github.com/ubports/messaging-app/issues/222
Thank you

**Comment by luksus42** [comment]
Hm, it turns out, that the mime type checker which is linked in the other thread, does not know the vorbis and opus codecs. I guess that it then randomly picks x-matroska... Another checker identifies the same file with ogg extension as video/vorbis and with oga extension as audio/vorbis.

Therefore I switched the ogg extension to oga (again, as it was some time before I changed it to ogg).
Could you please test, if this solves your problem?

[recorder.zip](https://github.com/luksus42/recorder/files/5343600/recorder.zip)
In the Zip is an armhf- and an arm64-version.

**Comment by lduboeuf** [comment]
sadly it doesn't work also:
![screenshot20201007_224133217](https://user-images.githubusercontent.com/11663835/95385796-bf521b80-08ee-11eb-9c7c-0708716f3406.png)

**Comment by luksus42** [comment]
@lduboeuf : as I said, this checker does not know ogg/vorbis at all. At least it is not listed underneath. So I doubt, that it gives a correct information, regarding that ogg/oga files.
There is also this js checker: there it is recognized ass audio/ogg:
https://stackblitz.com/edit/mime-type-checker

**Comment by lduboeuf** [comment]
oh yes sorry, well in messaging app it doezn't work, maybe Qt mimetype detection is not good also

**Comment by luksus42** [comment]
Just tried your testfile in the checker you mentioned, from the other thread, and it does get correctly recognized. So I have to apologize.
Hm strange.
I have no clue, how this matroska mime type gets in there...

**Comment by lduboeuf** [comment]
in messaging app, the mime type guessing is handled here: https://github.com/ubports/messaging-app/blob/xenial/src/messagingapplication.cpp#L314

**Comment by luksus42** [comment]
Interesting. I am using the same, for guessing the correct file-container with the given codec.
And that works. But it does not explain, where the mimeType is set and if it is even possible to set it.

**Comment by luksus42** [comment]
After further investigation, I have still no idea whats happening in the background (QMediaRecorder). Somehow it is muxing the vorbis audio stream into an matroska container... regardless of what container format I set.

**Comment by lduboeuf** [comment]
Yes strange, did some testings:
And the only way to get it recognized properly seems by forcing the mime type :-/
e.g: `m_audioRecorder->setEncodingSettings(m_audioSettings, QVideoEncoderSettings(), "audio/ogg");`

**Comment by luksus42** [comment]
Oh nice, I searched for a possibility to set the mimetype explicitly, but did not find it.

Sadly, I cannot work on it before next week.

Am Thu, 8 Oct 2020 00:18:43 -0700, Lionel Duboeuf schrieb:
> Yes strange, did some testings:
> And the only way to get it recognized properly seems by forcing 
> the mime type :-/
> e.g: `m_audioRecorder->setEncodingSettings(m_audioSettings, 
> QVideoEncoderSettings(), "audio/ogg");`
>

--

**Comment by luksus42** [comment]
Oh, I just saw it, does it use QVideoEncoderSettings and not QAudioEncoderSettings? Perhaps thats the culprit...
Anyway, I will have a look next week.

Am Thu, 8 Oct 2020 00:18:43 -0700, Lionel Duboeuf schrieb:
> Yes strange, did some testings:
> And the only way to get it recognized properly seems by forcing 
> the mime type :-/
> e.g: `m_audioRecorder->setEncodingSettings(m_audioSettings, 
> QVideoEncoderSettings(), "audio/ogg");`
>

--

**Comment by lduboeuf** [comment]
yeah i really don't know why, it is a code example found in github somewhere. Good luck ;-)

**Comment by luksus42** [comment]
Hi,
could you please test this version?
[audio-recorder.luksus_1.0.9.zip](https://github.com/luksus42/recorder/files/5381331/audio-recorder.luksus_1.0.9.zip)

So I still had to evaluate the right container-format manually in code. But the app now tries to resolve it automatically for the user, by the selected codec.
In order to choose manually a not automatically resolved container, I brought the container selection back in.
And note, that container-format is not equal to file-extension. The file-extension gets resolved separately by the mimetype of the codec.

Another note:
```
setEncodingSettings(m_audioSettings, QVideoEncoderSettings(), "audio/ogg");
```
This is not setting the mimetype, but the "container-format". (Whatever that means, the qt-documentation is not very helpful here...)
I do it in a similar way now.

**Comment by gbdomubpkm** [comment]
User tests :
- audio Vorbis ogg  good now. 👍
- A-Law, Mu-Law wav seems good
- Opus ogg seems good
- Flac file created even if i see
![Flac 20201015_030642802](https://user-images.githubusercontent.com/50362604/96067742-b63aee80-0e9a-11eb-91d6-5e2b521c65d9.png)
- Speex  spx, Amr amr don't work
![Speex 20201015_032040504](https://user-images.githubusercontent.com/50362604/96068103-73c5e180-0e9b-11eb-8bcf-842c4890c6b6.png)
![Amr 20201015_030856215](https://user-images.githubusercontent.com/50362604/96068144-8fc98300-0e9b-11eb-85d2-1e2511fdf216.png)
For Speex and Amr
![FAILED TO BUILT 20201015_030926113](https://user-images.githubusercontent.com/50362604/96068210-bdaec780-0e9b-11eb-9230-a2e178db6246.png)

**Comment by luksus42** [comment]
Are you still around and could you please test the following build?
- removed the container selection again, as it is confusing, when no container was found, but it still uses the right container (amr, spx, flac)
- added file extensions in records overview page
- added audio source selection in advanced settings view, which is useless on ubports because of pulseaudio, but can be useful on desktop devices

[audio-recorder_1.0.9.zip](https://github.com/luksus42/recorder/files/5808553/audio-recorder_1.0.9.zip)

**Comment by luksus42** [comment]
should be fixed with 8dc912c0739ae4fe69fc34cee28487b0ec8c0c53.
Feel free to open the issue again, if you encounter some related bugs.

**Comment by gbdomubpkm** [comment]
Ok. Thanks for your work.

**Comment by luksus42** [comment]
I already pushed the new version into the open-store, so you can just test there.
It's also more up to date, then the zip I posted above.

**Comment by gbdomubpkm** [comment]
I saw this. I'm too busy now but i will test more this we or quickly.

**Comment by luksus42** [comment]
alright, no need to hurry. ;-)
Thanks.

**Comment by gbdomubpkm** [comment]
Tested.
Overwhelmingly works very well.
But for me on the BQ E5 HD, fails to create systematically for .spx and .amr WITH 2 CHANNELS : works well on 1 channel.

Punctually and unpredictably, fails when starting a recording after changing the audio encoding. : this is solved by resetting the app parameters with UTTT.

I like the dark mode. 👍🏼
